### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by agnes-santos** [agnes-nuguid/portfolio-v0#1]
- [x] #0: Tech Stack
- [x] #1: My portfolio should have a welcome section with an id of welcome-section.
- [x] #2: The welcome section should have an h1 element that contains text.
- [x] #3: My portfolio should have a projects section with an id of projects.
- [x] #4: The projects section should contain at least one element with a class of project-tile to hold a project.
- [x] #5: The projects section should contain at least one link to a project.
- [x] #6: My portfolio should have a navbar with an id of navbar.
- [x] #7: The navbar should contain at least one link that I can click on to navigate to different sections of the page.
- [x] #8: My portfolio should have a link with an id of profile-link, which opens my GitHub or FCC profile in a new tab.
- [x] #9: My portfolio should have at least one media query.
- [x] #10: The height of the welcome section should be equal to the height of the viewport.
- [x] #11: The navbar should always be at the top of the viewport.

**Comment by agnes-santos** [comment]
![image](https://user-images.githubusercontent.com/22828458/100050430-5b5ec480-2e54-11eb-8c29-0732185fbe10.png)

**Comment by agnes-santos** [comment]
![image](https://user-images.githubusercontent.com/22828458/100050856-564e4500-2e55-11eb-8c18-16309d76e06d.png)

**Comment by agnes-santos** [comment]
![image](https://user-images.githubusercontent.com/22828458/100054084-50a82d80-2e5c-11eb-8788-1de5cfe93860.png)

**Comment by agnes-santos** [comment]
![image](https://user-images.githubusercontent.com/22828458/100055095-45ee9800-2e5e-11eb-8d16-591b46c6756f.png)

**Comment by agnes-santos** [comment]
![image](https://user-images.githubusercontent.com/22828458/100065279-8e15b680-2e6e-11eb-90b5-b525cb2dc030.png)

**Comment by agnes-santos** [comment]
![image](https://user-images.githubusercontent.com/22828458/100067229-f6fe2e00-2e70-11eb-8696-9c96fe7824cd.png)

**Comment by agnes-santos** [comment]
![image](https://user-images.githubusercontent.com/22828458/100072692-8d355280-2e77-11eb-96e7-d7abc663dafa.png)

**Comment by agnes-santos** [comment]
![image](https://user-images.githubusercontent.com/22828458/100074544-d7b7ce80-2e79-11eb-8405-b394e9d00b94.png)

**Comment by agnes-santos** [comment]
![image](https://user-images.githubusercontent.com/22828458/100077118-ef448680-2e7c-11eb-9365-5b1a17254989.png)

**Comment by agnes-santos** [comment]
![image](https://user-images.githubusercontent.com/22828458/100079808-12bd0080-2e80-11eb-9e9d-9ea1186ab66e.png)

**Comment by agnes-santos** [comment]
![image](https://user-images.githubusercontent.com/22828458/100083432-721d0f80-2e84-11eb-9e5d-483966276c87.png)
